### ISSUE TITLE
excessive permissions required?

### ISSUE THREAD

**Issue by vpereira** [camertron/scuttle-server#15]
I was looking into scuttle, however I'm kind of confused: Why does it require full access to my private information to read some models in read-only? 

![Screenshot_2019-12-04_16-09-47](https://user-images.githubusercontent.com/37418/70154311-9cdce980-16b0-11ea-936e-da1d4c444376.png)

**Comment by camertron** [comment]
Oof, thanks @vpereira. Looks like it's configured to ask for the "user" oauth scope, which I probably did without thinking too hard about it when I was trying to get this project off the ground.

It's not super clear to me which scope Scuttle should be using. Here's [a list](https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/) of the available scopes. I guess I want "repo"? Still gives write access to private repos, but I don't see anything else on the list that grants read-only access to privates. Sounds like it's a [long-standing](https://github.com/jollygoodcode/jollygoodcode.github.io/issues/6) [issue](https://github.com/dear-github/dear-github/issues/113).

For the time being I've switched the app over to using the "repo" scope and revoked all existing user tokens. That way Scuttle will ask everyone to auth again, but this time request a narrower set of permissions.
