### ISSUE TITLE
Is it possible to add PostgreSQL's "DISTINCT ON"?

### ISSUE THREAD

**Issue by leoarnold** [camertron/scuttle-server#34]
Not sure what the project's policy is on SQL dialect-specific features, but it would have saved me quite some time today if scuttle could have told me that

```sql
SELECT DISTINCT ON ( "things"."property" ), * FROM "things"
```

can be written as

```ruby
# Turned out to be wrong: See https://github.com/rails/arel/issues/302#issuecomment-53966070
Things
  .select(
    Arel::Nodes::DistinctOn.new(Things.arel_table[:property]),
    Arel.star
  )
```

**Comment by camertron** [comment]
Hey @leoarnold, thanks for asking about this. For the most part I try not to add dialect-specific functionality to Scuttle, but in this case because `DISTINCT ON` can be easily matched on I think an exception can be made. The tricky part will be getting the [SQL parser](https://github.com/camertron/SQLParser/blob/master/SQLParser.g4) to recognize it. Are you up for submitting a PR?

**Comment by leoarnold** [comment]
I just realized that the Arel code above is wrong: https://github.com/rails/arel/issues/302#issuecomment-53966070

There is a convenience method: https://github.com/rails/arel/pull/306, but it won't work with joins :grimacing:.

**Comment by camertron** [comment]
Huh why won't it work with joins?

**Comment by leoarnold** [comment]
Sorry, was a bit unclear there. Assume `User` belongs_to `Company` then

```ruby
users = User.arel_table
companies = Company.arel_table

select_manger = users
  .project(Arel.star)
  .distinct_on(users[:foo])
  .join(companies).on(users[:company_id].eq(companies[:id]))
  .where(users[:age].eq(33))

select_manger.to_sql
```

will give you the correct query, but I was not able to figure out how I can use it in the same way as

```ruby
Users.join(:company).includes(:company).where(users[:age].eq(33))
```

where it automatically loads the companies. And something like

```ruby
User.joins(:company).includes(:company).select(select_manger)
```

will just nest the query.

**Comment by leoarnold** [comment]
If anyone finds this through Google, I can suggest this monkey patch:

```ruby
# config/initializers/active_record_distinct_on.rb
module ActiveRecord
  class Base
    def self.distinct_on(column_name)
      all.distinct_on(column_name)
    end
  end

  class Relation
    def distinct_on(column_name)
      qualified_name = %("#{table.name}"."#{table[column_name].name}")

      selectors = select_values

      # Insert DISTINCT directly behind SELECT and re-append the original selection
      reselect("DISTINCT ON (#{qualified_name}) #{qualified_name}").select(selectors)
    end
  end
end
```

**Comment by camertron** [comment]
I don't have an app to test this in right now, but it feels like you should be able to use the active record API for this, i.e:

```ruby
User.select(Arel.star).distinct_on(:foo).join(:companies)
```

Is that what the monkeypatch enables?

**Comment by StanisLove** [comment]
> If anyone finds this through Google, I can suggest this monkey patch:
> 
> ```ruby
> # config/initializers/active_record_distinct_on.rb
> module ActiveRecord
>   class Base
>     def self.distinct_on(column_name)
>       all.distinct_on(column_name)
>     end
>   end
> 
>   class Relation
>     def distinct_on(column_name)
>       qualified_name = %("#{table.name}"."#{table[column_name].name}")
> 
>       selectors = select_values
> 
>       # Insert DISTINCT directly behind SELECT and re-append the original selection
>       reselect("DISTINCT ON (#{qualified_name}) #{qualified_name}").select(selectors)
>     end
>   end
> end
> ```

It would be more clear, just to define a scope
```ruby
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  scope :distinct_on, ->(*distinct_columns) {
    columns_str = distinct_columns.join(', ')
    reselect("DISTINCT ON (#{columns_str}) #{columns_str}").select(select_values)
  }
end
```
