### ISSUE TITLE
www.scuttle.io is down

### ISSUE THREAD

**Issue by WaKeMaTTa** [camertron/scuttle-server#41]
www.scuttle.io is down :cry:

**Comment by camertron** [comment]
Hey @WaKeMaTTa thanks for letting me know about this. I upgraded to a paid Heroku account before the deadline but apparently that wasn't enough to save Scuttle 😢 

It should be back up now though 😄

**Comment by WaKeMaTTa** [comment]
Thank you. Maybe you could migrate to fly.io the free plan should be enough for this small app. ;)

**Comment by camertron** [comment]
That's a great idea, I'll look into it!
