### ISSUE TITLE
Helpers checkbox

### ISSUE THREAD

**Issue by dankohn** [camertron/scuttle-server#7]
I mainly wanted to complement your amazing work here and in http://www.slideshare.net/camerondutro/advanced-arel-when-activerecord-just-isnt-enough .

I also wanted to suggest adding a checkbox for "Use helpers" that would display the Ruby code with:
```ruby
include Arel::Nodes
include ArelHelpers:ArelTable
```
at the top and then remove the `arel_table` and `Arel::Nodes::` accordingly.

I hope scuttle.io helps increase the popularity of using Arel in place of SQL strings.

**Comment by camertron** [comment]
Hey @dankohn this should be fixed now. Took today to address a bunch of Scuttle issues.
